from django.urls import path

from .views import (
    AuditLogApi,
    ChangeStatusApi,
    ClientListCreateApi,
    ClientRetrieveUpdateApi,
    EquipmentDocumentsApi,
    EquipmentListCreateApi,
    EquipmentRetrieveUpdateDestroyApi,
    GenerateDocumentApi,
    InspectApi,
    InspectionsListApi,
    LoginApi,
    LogoutApi,
    MarkReceiptPrintedApi,
    MarkSignedApi,
    MeApi,
    ReservationCancelApi,
    ReservationCompleteApi,
    ReservationsListApi,
    ReserveApi,
    StatusHistoryApi,
)

urlpatterns = [
    path('auth/login', LoginApi.as_view()),
    path('auth/logout', LogoutApi.as_view()),
    path('auth/me', MeApi.as_view()),
    path('equipment', EquipmentListCreateApi.as_view()),
    path('equipment/<int:pk>', EquipmentRetrieveUpdateDestroyApi.as_view()),
    path('equipment/<int:pk>/change-status', ChangeStatusApi.as_view()),
    path('clients', ClientListCreateApi.as_view()),
    path('clients/<int:pk>', ClientRetrieveUpdateApi.as_view()),
    path('reservations', ReservationsListApi.as_view()),
    path('equipment/<int:pk>/reserve', ReserveApi.as_view()),
    path('reservations/<int:pk>/cancel', ReservationCancelApi.as_view()),
    path('reservations/<int:pk>/complete', ReservationCompleteApi.as_view()),
    path('equipment/<int:pk>/inspect', InspectApi.as_view()),
    path('inspections', InspectionsListApi.as_view()),
    path('equipment/<int:pk>/documents', EquipmentDocumentsApi.as_view()),
    path('equipment/<int:pk>/documents/generate', GenerateDocumentApi.as_view()),
    path('documents/<int:pk>/mark-signed', MarkSignedApi.as_view()),
    path('equipment/<int:pk>/mark-receipt-printed', MarkReceiptPrintedApi.as_view()),
    path('equipment/<int:pk>/status-history', StatusHistoryApi.as_view()),
    path('audit-log', AuditLogApi.as_view()),
]
